# For more information on how to configure kitty, see the kitty
# https://sw.kovidgoyal.net/kitty/conf/

#: Font configuration {{{
font_size 16.0

#: }}}

#: Mouse {{{

open_url_with default
detect_urls yes
underline_hyperlinks hover
copy_on_select yes

#: }}}

#: Terminal bell {{{

enable_audio_bell yes
window_alert_on_bell yes
bell_on_tab "🔔 "

#: }}}

#: Color scheme {{{

#: Base on Wonderland
foreground #f6f8fa
background #24292e
background_opacity 0.85
background_blur 40

#: }}}

#: Behavior {{{

allow_hyperlinks yes
shell_integration enabled
macos_titlebar_color system

#:}}}

#: Keyboard shortcuts {{{

#: Maps keys to support <Ctrl-Shift-{h,j,k,l}> for pane navigation
#: on TMUX and VIM.
map ctrl+shift+k send_text \033[1;6A
map ctrl+shift+j send_text \033[1;6B
map ctrl+shift+h send_text \033[1;6D
map ctrl+shift+l send_text \033[1;6C

#: kitty_mod is the modifier key that is used to modify the behavior of
#: the keyboard shortcuts. 
kitty_mod ctrl+shift

##: Clipboard {{{

#: Copy to clipboard

map kitty_mod+c copy_to_clipboard
map cmd+c       copy_to_clipboard

#: Paste from clipboard

map kitty_mod+v paste_from_clipboard
map cmd+v       paste_from_clipboard

#: }}}

#: }}}
